source "https://rubygems.org"

gem "rouge"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-paginate-content"
gem "json"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "webrick", "~> 1.8"
gem "kramdown-parser-gfm"
gem "http_parser", "~> 0.1.3"
